@hostname = http://localhost:3000/api

### Add products as a seed only in dev environment
GET {{hostname}}/seed HTTP/1.1

### GetProducts by gender, default gender=all
GET {{hostname}}/products?gender=men HTTP/1.1

### GetProducts by slug
GET {{hostname}}/products/mens_chill_crew_neck_sweatshirt HTTP/1.1

### SearchProducts by query at (title and tags)
GET {{hostname}}/search/shirt HTTP/1.1

### Login
POST {{hostname}}/user/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=juan@gmail.com
&pwd=123456

### Register user
POST {{hostname}}/user/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=Alex Goe
&email=alex@gmail.com
&pwd=123456
